name: 自动化测试流水线
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_task:
    runs-on: ubuntu-latest
    steps:
      - name: 检出项目代码
        uses: actions/checkout@v4

      - name: 配置Python3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # 彻底移除cache: pip，消除依赖文件校验

      - name: 安装测试依赖
        run: |
          pip install pytest requests pytest-html

      - name: 运行自动化用例
        run: pytest tests/ --html=test_report.html

      - name: 存档测试报告
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 自动化测试结果报告
          path: test_report.html
